# Generated by Django 3.0.7 on 2020-07-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0002_eventlogdata_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlogdata',
            old_name='transactionId',
            new_name='assigningAccountId',
        ),
    ]
