# Generated by Django 3.0.7 on 2020-06-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SGXData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('secretKey', models.CharField(max_length=256)),
                ('msg0', models.CharField(max_length=256)),
                ('msg1', models.CharField(max_length=256)),
                ('msg2', models.CharField(max_length=256)),
                ('msg3', models.CharField(max_length=256)),
                ('msg4', models.CharField(max_length=256)),
            ],
        ),
    ]
