# Generated by Django 3.0.7 on 2020-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intel_SGX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAttestationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('data', models.CharField(max_length=25600)),
            ],
        ),
    ]
