# Generated by Django 3.0.7 on 2020-07-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intel_SGX', '0002_remoteattestationdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteAttestationData',
        ),
        migrations.DeleteModel(
            name='SGXData',
        ),
    ]
