# Generated by Django 3.0.7 on 2020-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Intel_SGX', '0003_auto_20200728_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=256)),
                ('accountId', models.CharField(max_length=256)),
                ('transactionId', models.CharField(max_length=256)),
                ('ipfsHash', models.CharField(max_length=256)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('policeStationId', models.CharField(max_length=256)),
            ],
        ),
    ]
