# Generated by Django 3.0.7 on 2020-07-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intel_SGX', '0004_eventlogdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventLogData',
        ),
    ]
